name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain

    - name: Build Backend
      shell: msys2 {0}
      run: |
        cd backend
        CGO_ENABLED=1 go build -v -o pewpawd.exe .

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        arch: 'win64_mingw'

    - name: Build Frontend
      shell: msys2 {0}
      run: |
        cd frontend
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
